const foodItem = [
  {
    id: 1,
    name: "Ambur Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Hyderabad Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "images/biryani/b2.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "egg Biryani",
    category: "biryani",
    rating: 4.3,
    price: 18,
    img: "images/biryani/b3.jpeg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "images/biryani/b4.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Sindhi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 18,
    img: "images/biryani/b5.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "malabar Biryani",
    category: "biryani",
    rating: 4.3,
    price: 21,
    img: "images/biryani/b6.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: " chicken",
    category: "Chicken",
    rating: 4.3,
    price: 20,
    img: "images/chicken/c1.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Chilly chicken",
    category: "Chicken",
    rating: 4.3,
    price: 20,
    img: "images/chicken/c2.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "hot chicken",
    category: "Chicken",
    rating: 4.3,
    price: 20,
    img: "images/chicken/c3.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "tandoori  chicken",
    category: "Chicken",
    rating: 4.3,
    price: 20,
    img: "images/chicken/c4.jpg",
    quantity: 1,
  },
  {
    id: 11,
    name: "fried chicken",
    category: "Chicken",
    rating: 4.3,
    price: 27,
    img: "images/chicken/c5.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: " chicken tikka",
    category: "Chicken",
    rating: 4.3,
    price: 20,
    img: "images/paneer/c6.jpg",
    quantity: 1,
  },
  {
    id: 13,
    name: " chilli paneer ",
    category: "Paneer",
    rating: 4.3,
    price: 20,
    img: "images/paneer/p1.jpg",
    quantity: 1,
  },

  {
    id: 14,
    name: "matar paneer",
    category: "Paneer ",
    rating: 4.3,
    price: 23,
    img: "images/paneer/p2.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "kadhai paneer",
    category: "Paneer ",
    rating: 4.3,
    price: 20,
    img: "images/paneer/p3.jpg",
    quantity: 1,
  },
  {
    id: 16,
    name: "paneer tikka",
    category: "Paneer ",
    rating: 4.3,
    price: 20,
    img: "images/paneer/p4.jpg",
    quantity: 1,
  },
  {
    id: 17,
    name: "palak paneer",
    category: "Paneer ",
    rating: 4.3,
    price: 20,
    img: "images/paneer/p5.jpg",
    quantity: 1,
  },
  {
    id: 18,
    name: "kaju paneer",
    category: "Paneer",
    rating: 4.3,
    price: 20,
    img: "images/paneer/p6.jpg",
    quantity: 1,
  },
  {
    id: 19,
    name: "chowmin",
    category: "chinese",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 20,
    name: "munchurian",
    category: "chinese",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 21,
    name: "gravy munchurian",
    category: "chinese",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 22,
    name: "pasta",
    category: "chinese",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 23,
    name: "noodles",
    category: "chinese",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 24,
    name: "french fries",
    category: "chinese",
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 25,
    name: "idli-sambhar",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },

  {
    id: 26,
    name: "plain dosa",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 27,
    name: "masala dosa",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 28,
    name: "sambhar vada",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 29,
    name: "uttapam",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
  {
    id: 30,
    name: "rasam",
    category: "southIndian",
    rating: 4.3,
    price: 20,
    img: "images/biryani/amburbiryani.jpg",
    quantity: 1,
  },
];
export { foodItem };
